/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modell.Proveedor;
import servicioBD.serviciodb;

/**
 *
 * @author jean
 */
public class Consultaproveedor extends javax.swing.JFrame {

    /**
     * Creates new form Consultaproveedor
     */
     public void Sletras(JTextField a){
        a.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                char c= e.getKeyChar();
                if(Character.isDigit(c))
                    e.consume();
            }
        });
    }
       public void Nletras(JTextField a){
        a.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                char c= e.getKeyChar();
                if(!Character.isDigit(c))
                    e.consume();
            }
        });
    }
    public Consultaproveedor() {
        initComponents();
        MostrarDatos();
        DeshabilitarBotones();
        DeshabilitarCampos();
    }
    
    void Limpiar(){
        this.RutField.setText("");
        this.NombreField.setText("");
        this.TelefonoField.setText("");
        this.DireccionField.setText("");
        this.EmailField.setText("");
        this.PaginaField.setText("");
    }
    void HabilitarCampos(){
        TelefonoField.setEnabled(true);
        NombreField.setEnabled(true);
        RutField.setEnabled(true);
        DireccionField.setEnabled(true);
        EmailField.setEnabled(true);
        PaginaField.setEnabled(true);
    }
    void DeshabilitarCampos(){
        TelefonoField.setEnabled(false);
        NombreField.setEnabled(false);
        RutField.setEnabled(false);
        DireccionField.setEnabled(false);
        EmailField.setEnabled(false);
        PaginaField.setEnabled(false);
    }
    void DeshabilitarBotones(){
        EliminarBoton.setEnabled(false);
        ModificarBoton.setEnabled(false);
        GuardarBoton.setEnabled(false);
    }
    boolean CamposLlenos(){
          boolean pregunta = false;
          if(this.RutField.getText().equals("")==true||this.NombreField.getText().equals("")==true||this.TelefonoField.getText().equals("")==true){
          }else pregunta=true;
          return pregunta;
    }
    
    void MostrarDatos(){
        ArrayList<Proveedor> proveedores = new ArrayList<Proveedor>();
        serviciodb serv = new serviciodb();
        proveedores = serv.getProveedor();
                
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("Rut");
        modelo.addColumn("Nombre");
        modelo.addColumn("Telefono");
        modelo.addColumn("Email");
        modelo.addColumn("Pagina web");
        modelo.addColumn("Direccion");
        ProveedorTable.setModel(modelo);
        
        String []datos=new String[6];
        Iterator<Proveedor> ite=proveedores.iterator();
        while(ite.hasNext()){
        Proveedor proveedor1= ite.next();
            datos[0]=proveedor1.getId_rut().toString();
            datos[1]=proveedor1.getNombre();
            datos[2]=proveedor1.getTelefono().toString();
            datos[3]=proveedor1.getEmail();
            datos[4]=proveedor1.getPaginaweb();
            datos[5]=proveedor1.getDireccion();
            
            modelo.addRow(datos);
        
        }
        ProveedorTable.setModel(modelo);
        Limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscarLabel = new javax.swing.JLabel();
        BuscarField = new javax.swing.JTextField();
        BuscarButton = new javax.swing.JButton();
        MostrarTodoBoton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProveedorTable = new javax.swing.JTable();
        RutProveedor = new javax.swing.JLabel();
        RutField = new javax.swing.JTextField();
        NombreField = new javax.swing.JTextField();
        NombreLabel = new javax.swing.JLabel();
        TelefonoLabel = new javax.swing.JLabel();
        TelefonoField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        PaginaLabel = new javax.swing.JLabel();
        PaginaField = new javax.swing.JTextField();
        DireccionField = new javax.swing.JTextField();
        DireccionLabel = new javax.swing.JLabel();
        ModificarBoton = new javax.swing.JButton();
        EliminarBoton = new javax.swing.JButton();
        NuevoBoton = new javax.swing.JButton();
        GuardarBoton = new javax.swing.JButton();
        AtrasButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("PROVEEDORES"));

        buscarLabel.setText("Buscar por nombre:");

        BuscarField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BuscarFieldKeyTyped(evt);
            }
        });

        BuscarButton.setText("Buscar");
        BuscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarButtonActionPerformed(evt);
            }
        });

        MostrarTodoBoton.setText("Mostrar todos");
        MostrarTodoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarTodoBotonActionPerformed(evt);
            }
        });

        ProveedorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        ProveedorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProveedorTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProveedorTable);

        RutProveedor.setText("Rut Proveedor");

        NombreField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreFieldKeyTyped(evt);
            }
        });

        NombreLabel.setText("Nombre");

        TelefonoLabel.setText("Teléfono");

        TelefonoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoFieldActionPerformed(evt);
            }
        });
        TelefonoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoFieldKeyTyped(evt);
            }
        });

        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });

        EmailLabel.setText("Email");

        PaginaLabel.setText("Página Web");

        DireccionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionFieldActionPerformed(evt);
            }
        });

        DireccionLabel.setText("Dirección");

        ModificarBoton.setText("Modificar");
        ModificarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBotonActionPerformed(evt);
            }
        });

        EliminarBoton.setText("Eliminar");
        EliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBotonActionPerformed(evt);
            }
        });

        NuevoBoton.setText("Nuevo");
        NuevoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoBotonActionPerformed(evt);
            }
        });

        GuardarBoton.setText("Guardar nuevo");
        GuardarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBotonActionPerformed(evt);
            }
        });

        AtrasButton.setText("Volver al menú principal");
        AtrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buscarLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BuscarField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BuscarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MostrarTodoBoton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(RutProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NombreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TelefonoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PaginaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(DireccionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ModificarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NuevoBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GuardarBoton)
                                .addGap(1, 1, 1))
                            .addComponent(DireccionField)
                            .addComponent(PaginaField)
                            .addComponent(EmailField)
                            .addComponent(TelefonoField)
                            .addComponent(NombreField)
                            .addComponent(RutField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AtrasButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarLabel)
                    .addComponent(BuscarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarButton)
                    .addComponent(MostrarTodoBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RutField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TelefonoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TelefonoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailLabel))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PaginaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PaginaLabel)))
                    .addComponent(RutProveedor))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DireccionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DireccionLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModificarBoton)
                    .addComponent(EliminarBoton)
                    .addComponent(NuevoBoton)
                    .addComponent(GuardarBoton))
                .addGap(23, 23, 23)
                .addComponent(AtrasButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasButtonActionPerformed
        Sistema sistema = new Sistema();
        sistema.setVisible(true);
        sistema.setLocationRelativeTo(null);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_AtrasButtonActionPerformed

    private void BuscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarButtonActionPerformed
        DeshabilitarBotones();
        DeshabilitarCampos();
        Limpiar();
        modell.Proveedor proveedor1 = new modell.Proveedor();
        serviciodb serv = new serviciodb();
        String nombrepro= this.BuscarField.getText();
        proveedor1 = serv.getBuscarProveedor(nombrepro);
      
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("Rut");
        modelo.addColumn("Nombre");
        modelo.addColumn("Telefono");
        modelo.addColumn("Email");
        modelo.addColumn("Pagina web");
        modelo.addColumn("Direccion");
        ProveedorTable.setModel(modelo);   
        
        String []datos=new String[6];
        // al ingresar proveedor, nombre nunca puede ser null!!!
        //if(proveedor1.getNombre().equals(null)==false){ //condicionar si es null o no
            datos[0]=proveedor1.getId_rut().toString();
            datos[1]=proveedor1.getNombre();
            datos[2]=proveedor1.getTelefono().toString();
            datos[3]=proveedor1.getEmail();
            datos[4]=proveedor1.getPaginaweb();
            datos[5]=proveedor1.getDireccion();
            modelo.addRow(datos);
        
        
        
        //else JOptionPane.showMessageDialog(rootPane, "No existen datos para el proveedor");
                  
        ProveedorTable.setModel(modelo);
        Limpiar();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarButtonActionPerformed

    private void MostrarTodoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarTodoBotonActionPerformed
        MostrarDatos();
    }//GEN-LAST:event_MostrarTodoBotonActionPerformed

    private void TelefonoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoFieldActionPerformed

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void DireccionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionFieldActionPerformed

    private void ModificarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBotonActionPerformed
        if(CamposLlenos()==true){
            Proveedor proveedor=new Proveedor();
            int fila = ProveedorTable.getSelectedRow();
            String sql= ProveedorTable.getValueAt(fila, 0).toString();
            //NO MODIFICAR LLAVES!
            proveedor.setNombre(this.NombreField.getText());
            proveedor.setTelefono(Integer.parseInt(this.TelefonoField.getText()));
            proveedor.setEmail(this.EmailField.getText());
            proveedor.setPaginaweb(this.PaginaField.getText());
            proveedor.setDireccion(this.DireccionField.getText());
            

            serviciodb serv = new serviciodb();
            boolean pregunta = serv.modificarProveedor(sql,proveedor);
            if(pregunta==true){
                JOptionPane.showMessageDialog(null,"El producto fue modificado con éxito", null, WIDTH);
            }else
            JOptionPane.showMessageDialog(null,"Ocurrió algún error", null, WIDTH);
            Limpiar();
            MostrarDatos();
            DeshabilitarBotones();
            DeshabilitarCampos();
        }else
        JOptionPane.showMessageDialog(null,"Debe llenar todos los campos", null, WIDTH);

    }//GEN-LAST:event_ModificarBotonActionPerformed

    private void EliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBotonActionPerformed
        boolean pregunta=false;
        int respuesta = JOptionPane.showConfirmDialog(null,"¿Seguro que desea eliminar este Proveedor?" , null,JOptionPane.CANCEL_OPTION);
        if (respuesta == JOptionPane.YES_OPTION){
            int fila = ProveedorTable.getSelectedRow();
            String sql= "delete from proveedor where id_rut=" + ProveedorTable.getValueAt(fila, 0);
            serviciodb serv = new serviciodb();
            pregunta=serv.eliminarProducto(sql);
            if(pregunta==true){
                JOptionPane.showMessageDialog(null,"El proveedor fue eliminado con éxito", null, WIDTH);
            }}
            if(pregunta==false) JOptionPane.showMessageDialog(null,"Ocurrió algún error", null, WIDTH);

            Limpiar();
            MostrarDatos();
            DeshabilitarBotones();
            DeshabilitarCampos();
    }//GEN-LAST:event_EliminarBotonActionPerformed

    private void NuevoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoBotonActionPerformed
        MostrarDatos();
        Limpiar();
        EliminarBoton.setEnabled(false);
        ModificarBoton.setEnabled(false);
        GuardarBoton.setEnabled(true);
        HabilitarCampos();
    }//GEN-LAST:event_NuevoBotonActionPerformed

    private void GuardarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBotonActionPerformed
        if(CamposLlenos()==true){
            Proveedor proveedor= new Proveedor();
            proveedor.setId_rut(Integer.parseInt(this.RutField.getText()));
            proveedor.setNombre(this.NombreField.getText());
            proveedor.setEmail(this.EmailField.getText());
            proveedor.setDireccion(this.DireccionField.getText());
            proveedor.setPaginaweb(this.PaginaField.getText());
            proveedor.setTelefono(Integer.parseInt(this.TelefonoField.getText()));

            serviciodb serv = new serviciodb();
            boolean pregunta = serv.setProveedor(proveedor);
            if(pregunta==true){
                JOptionPane.showMessageDialog(null,"El proveedor fue guardado con éxito", null, WIDTH);
                Limpiar();
            }else
                JOptionPane.showMessageDialog(null,"Ocurrió algún error", null, WIDTH);
            MostrarDatos();
            DeshabilitarBotones();
            DeshabilitarCampos();
        }else{
            JOptionPane.showMessageDialog(null,"Debe llenar por lo menos Rut, Nombre y Telefono", null, WIDTH);
        }
    }//GEN-LAST:event_GuardarBotonActionPerformed

    private void ProveedorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProveedorTableMouseClicked
        // TODO add your handling code here:
        HabilitarCampos();
        RutField.setEnabled(false);

        Proveedor proveedor=new Proveedor();
        if(evt.getButton()==1){
            int fila = ProveedorTable.getSelectedRow();
            int id= Integer.parseInt(ProveedorTable.getValueAt(fila, 0).toString());
            serviciodb serv = new serviciodb();
            proveedor=serv.getBuscarProveedor(id);
            
            this.RutField.setText(proveedor.getId_rut().toString());
            this.TelefonoField.setText(proveedor.getTelefono().toString());
            this.NombreField.setText(proveedor.getNombre());
            this.EmailField.setText(proveedor.getEmail());
            this.PaginaField.setText(proveedor.getPaginaweb());
            this.DireccionField.setText(proveedor.getDireccion());
            EliminarBoton.setEnabled(true);
            ModificarBoton.setEnabled(true);
            GuardarBoton.setEnabled(false);

        }
    }//GEN-LAST:event_ProveedorTableMouseClicked

    private void BuscarFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarFieldKeyTyped
    Sletras(BuscarField);        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarFieldKeyTyped

    private void NombreFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreFieldKeyTyped
    Sletras(NombreField);        // TODO add your handling code here:
    }//GEN-LAST:event_NombreFieldKeyTyped

    private void TelefonoFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoFieldKeyTyped
    Nletras(TelefonoField);        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultaproveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultaproveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultaproveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultaproveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultaproveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtrasButton;
    private javax.swing.JButton BuscarButton;
    private javax.swing.JTextField BuscarField;
    private javax.swing.JTextField DireccionField;
    private javax.swing.JLabel DireccionLabel;
    private javax.swing.JButton EliminarBoton;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JButton GuardarBoton;
    private javax.swing.JButton ModificarBoton;
    private javax.swing.JButton MostrarTodoBoton;
    private javax.swing.JTextField NombreField;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JButton NuevoBoton;
    private javax.swing.JTextField PaginaField;
    private javax.swing.JLabel PaginaLabel;
    private javax.swing.JTable ProveedorTable;
    private javax.swing.JTextField RutField;
    private javax.swing.JLabel RutProveedor;
    private javax.swing.JTextField TelefonoField;
    private javax.swing.JLabel TelefonoLabel;
    private javax.swing.JLabel buscarLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
