/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import modell.Usuario;
import servicioBD.serviciodb;

/**
 *
 * @author jeanc_000
 */
public class Loginn extends javax.swing.JFrame {

    /**
     * Creates new form Loginn
     */
    public Loginn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NombreLabel = new javax.swing.JLabel();
        NombreField = new javax.swing.JTextField();
        ClaveLabel = new javax.swing.JLabel();
        PassField = new javax.swing.JPasswordField();
        CancelarBoton = new javax.swing.JToggleButton();
        AceptarBoton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 3, true), "INGRESAR", javax.swing.border.TitledBorder.TRAILING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(51, 153, 255))); // NOI18N

        NombreLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        NombreLabel.setText("Nombre");

        ClaveLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ClaveLabel.setText("Clave");

        CancelarBoton.setText("Cancelar");
        CancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBotonActionPerformed(evt);
            }
        });

        AceptarBoton.setText("Aceptar");
        AceptarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AceptarBotonMouseClicked(evt);
            }
        });
        AceptarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarBotonActionPerformed(evt);
            }
        });

        jButton1.setText("ADMIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreLabel)
                    .addComponent(ClaveLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AceptarBoton)
                        .addGap(44, 44, 44)
                        .addComponent(CancelarBoton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(PassField)
                    .addComponent(NombreField))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreLabel))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClaveLabel)
                    .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AceptarBoton)
                    .addComponent(CancelarBoton)
                    .addComponent(jButton1))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBotonActionPerformed
        JOptionPane.showMessageDialog(null, "buenas tardes");
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarBotonActionPerformed

    private void AceptarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarBotonActionPerformed
                  
        if (this.NombreField.getText().equals("") || this.PassField.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe llenar todos los campos");
        } else {
            Usuario usuario = new Usuario();
            usuario.setUsuario(this.NombreField.getText());
            usuario.setPass(this.PassField.getText());
            serviciodb serv = new serviciodb();
            ArrayList<Usuario> usuario2 = new ArrayList <Usuario>();
            usuario2 = serv.getUsuarios();
            Iterator<Usuario>ite= usuario2.iterator();
            while(ite.hasNext()){
            Usuario usuarioaux= ite.next();
            
                if( usuarioaux.getPass().equals(usuario.getPass()) && usuarioaux.getUsuario().equals(usuario.getUsuario()))
                {// JOptionPane.showMessageDialog(rootPane,"Algun campo no funciona");else {
                Sistema menu = new Sistema();
                menu.setVisible(true);
                menu.setLocationRelativeTo(null);
                this.dispose();
                }
        }
        String nom=this.NombreField.getText();
    Sistema.UsuarioLabel.setText(nom);
    }//GEN-LAST:event_AceptarBotonActionPerformed
    }
    
    private void AceptarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarBotonMouseClicked
   /*     if (this.NombreField.getText().equals("") || this.PassField.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe llenar todos los campos");
        } else {
            Usuario usuario = new Usuario();
            usuario.setUsuario(this.NombreField.getText());
            usuario.setPass(this.PassField.getText());
            serviciodb serv = new serviciodb();
            
            Usuario usuario2 = new Usuario();
            usuario2 = serv.getUsuario();
            if(usuario2.getPass().equals(usuario.getPass()) && usuario2.getUsuario().equals(usuario.getUsuario())){
                Sistema menu = new Sistema();
                JOptionPane.showMessageDialog(rootPane,"entro al 2");
                menu.setVisible(true);
                menu.setLocationRelativeTo(null);
                this.dispose();
               
                
            }else
            JOptionPane.showMessageDialog(rootPane,"Contraseña o usuario invalido");
        }*/        // TODO add your handling code here:
    }//GEN-LAST:event_AceptarBotonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                Registrar registrar = new Registrar();
                registrar.setVisible(true);
                registrar.setLocationRelativeTo(null);
                this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarBoton;
    private javax.swing.JToggleButton CancelarBoton;
    private javax.swing.JLabel ClaveLabel;
    private javax.swing.JTextField NombreField;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
